FROM golang:1.25-alpine AS build

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -tags lambda.norpc -o /out/bootstrap ./cmd/lambda

FROM public.ecr.aws/lambda/provided:al2023

COPY --from=build /out/bootstrap ${LAMBDA_RUNTIME_DIR}/bootstrap
COPY config.yaml workflow.yaml /var/task/
CMD ["bootstrap"]
